name: notesappbloc
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  freezed_annotation: ^2.4.2
  json_annotation: ^4.8.1
  fluttertoast: ^8.2.4
  another_flushbar: ^1.12.30
  equatable: ^2.0.5
  flutter_secure_storage: ^9.0.0
  freezed: ^2.4.7
  http: ^1.2.2
  change_app_package_name: ^1.4.0
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.3
  firebase_auth: ^5.3.3
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.3
  intl: ^0.19.0
  flutter_staggered_grid_view: ^0.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  json_serializable: ^6.7.1


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf