name: notesappbloc
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.3
  firebase_auth: ^5.3.3




dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  json_serializable: ^6.7.1


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf